/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ptit.View;

import com.ptit.Model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author trang
 */
public class ManagerHomeFrm extends javax.swing.JFrame {
    private User user;

    /**
     * Creates new form ManagerHomeFrm
     */
    public ManagerHomeFrm(User user) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.user = user;
        
        jLabelHello.setText("Welcome back, " + user.getFullname() + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonQLNV = new javax.swing.JButton();
        jButtonStat = new javax.swing.JButton();
        jButtonRule = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelHello = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonQLNV.setText("Quản lý nhân viên");
        jButtonQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQLNVActionPerformed(evt);
            }
        });

        jButtonStat.setText("Xem báo cáo");
        jButtonStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatActionPerformed(evt);
            }
        });

        jButtonRule.setText("Nhận xe");
        jButtonRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRuleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("Trang chủ quản lý");

        jLabelHello.setText("Hello");

        jButtonLogout.setText("Đăng xuất");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonStat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelHello)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLogout)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHello)
                    .addComponent(jButtonLogout))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jButtonQLNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonStat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRule)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQLNVActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "This function is under construction!");
    }//GEN-LAST:event_jButtonQLNVActionPerformed

    private void jButtonRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRuleActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Sai thông tin đăng nhập!");
    }//GEN-LAST:event_jButtonRuleActionPerformed

    private void jButtonStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StatFrm statFrm = new StatFrm(this.user);
        statFrm.setVisible(true);
        statFrm.setTitle("Car Garage");
    }//GEN-LAST:event_jButtonStatActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this,
            "Bạn có muốn đăng xuất không?",
            "Đăng xuất",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

    // Kiểm tra phản hồi của người dùng
    if (response == JOptionPane.YES_OPTION) {
        // Nếu người dùng chọn Yes, hiển thị thông báo đăng xuất thành công
        JOptionPane.showMessageDialog(this, "Đăng xuất thành công!");
        // Đóng frame hiện tại
        this.dispose();
        // Chuyển về màn hình đăng nhập
        LoginFrm loginFrm = new LoginFrm();
        loginFrm.setVisible(true);
        loginFrm.setTitle("Đăng nhập");

    } else {
        // Nếu người dùng chọn No, không làm gì cả
        // JOptionPane sẽ tự động ẩn
    }
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerHomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerHomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerHomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerHomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ManagerHomeFrm(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonQLNV;
    private javax.swing.JButton jButtonRule;
    private javax.swing.JButton jButtonStat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelHello;
    // End of variables declaration//GEN-END:variables
}
