/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ptit.View;

import com.ptit.Model.IncomeStat;
import com.ptit.Model.Receipt;
import com.ptit.Model.RepairedCar;
import com.ptit.Model.UsedService;
import com.ptit.Model.UsedSupply;
import java.text.DecimalFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trang
 */
public class ReceiptDetailFrm extends javax.swing.JFrame {
    Receipt receipt;

    /**
     * Creates new form ReceiptDetailFrm
     */
    public ReceiptDetailFrm(Receipt r) {
        this.receipt = r;
        initComponents();
        
        jLabelReceiptID.setText("Mã HĐ: " + Integer.toString(receipt.getId()));        
//        jLabelCarAutomaker.setText("Hãng xe: " + receipt.getCar().getAutomaker());
//        jLabelCarLicense.setText("Biển số: " + receipt.getCar().getLicensePlate());
//        jLabelCarType.setText("Dòng xe: " + receipt.getCar().getType());
        jLabelCusAddress.setText("Địa chỉ: " + receipt.getCustomer().getAddress());
        jLabelCusName.setText("Họ tên: " + receipt.getCustomer().getName());
        jLabelCusTel.setText("Số điện thoại:" + receipt.getCustomer().getTel());
        jLabelEmEmail.setText("Email: " + receipt.getCreator().getEmail());
        jLabelEmName.setText("Họ tên: " + receipt.getCreator().getFullname());
        jLabelEmTel.setText("Số điện thoại: " + receipt.getCreator().getTel());
        
        double totalPrice = 0;
        for (RepairedCar rc : r.getRepairedCars()) {
            totalPrice += rc.getUsedServices().stream().mapToDouble(UsedService::getPrice).sum() + rc.getUsedSupplies().stream().mapToDouble(UsedSupply::getPrice).sum();
        }


        DecimalFormat decimalFormat = new DecimalFormat("#,###");
        
        String price = decimalFormat.format(totalPrice);
        jLabelTotalMoney.setText("Tổng tiền: " + price);
        
        if(receipt.getPaymentType().equals("cash")) {
            jLabelCashMoney.setText("Khách tiền mặt: " + price);
            jLabelTransferMoney.setText("Khách chuyển khoản: " + "0");
        } else {
            jLabelCashMoney.setText("Khách tiền mặt: " + "0");
            jLabelTransferMoney.setText("Khách chuyển khoản: " + price);
        }
        
        DefaultTableModel model = (DefaultTableModel) this.jTableListCar.getModel();
        model.setRowCount(0);
        
        for (RepairedCar rc : receipt.getRepairedCars()) {
            model.addRow(new Object[]{
                rc.getCar().getLicensePlate(),
                rc.getCar().getType(),
                rc.getCar().getAutomaker()
            });  
            loadReceipt(rc);
        }

    }
    
    void loadReceipt(RepairedCar rc) {
        if (!rc.getUsedSupplies().isEmpty()) {
            loadUsedSupply(rc);
        } else {
            jLabelListSupply.setText("Không có linh kiện");
        }
        
        if (!rc.getUsedServices().isEmpty()) {
            loadUsedService(rc);
        } else {
            jLabelListService.setText("Không có dịch vụ");
        }

    }
    
    void loadUsedSupply(RepairedCar rc) {
        DefaultTableModel model = (DefaultTableModel) this.jTableUsedSupply.getModel();
        model.setRowCount(0);
        for (UsedSupply uss : rc.getUsedSupplies()) {
            model.addRow(new Object[]{
                uss.getId(),
                uss.getSupply().getName(),
                uss.getSupply().getPrice(),
                uss.getAmount(),
                uss.getSupply().getUnit(),
                uss.getPrice()
            });
        }
    }
    
    void loadUsedService(RepairedCar rc) {
        DefaultTableModel model = (DefaultTableModel) this.jTableUsedService.getModel();
        model.setRowCount(0);
        for (UsedService us : rc.getUsedServices()) {
            model.addRow(new Object[]{
                us.getId(),
                us.getService().getName(),
                us.getService().getPrice(),
                us.getAmount(),
                us.getService().getUnit(),
                us.getPrice()
            });            
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelListSupply = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUsedSupply = new javax.swing.JTable();
        jLabelListService = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableUsedService = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jLabelEmName = new javax.swing.JLabel();
        jLabelEmTel = new javax.swing.JLabel();
        jLabelEmEmail = new javax.swing.JLabel();
        jLabelCusName = new javax.swing.JLabel();
        jLabelCusTel = new javax.swing.JLabel();
        jLabelCusAddress = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabelReceiptID = new javax.swing.JLabel();
        jLabelTotalMoney = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelCashMoney = new javax.swing.JLabel();
        jLabelTransferMoney = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableListCar = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel15.setText("Khách tiền mặt");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("Hóa đơn thanh toán");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Thông tin nhân viên");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Thông tin khách hàng");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Thông tin xe");

        jLabelListSupply.setText("Danh sách linh kiện");

        jTableUsedSupply.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên", "Đơn giá", "Số lượng", "Đơn vị tính", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableUsedSupply);

        jLabelListService.setText("Danh sách dịch vụ");

        jTableUsedService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên", "Đơn giá", "Số lượng", "Đơn vị tính", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableUsedService);

        jButtonBack.setText("Trở lại");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelEmName.setText("TênNV");

        jLabelEmTel.setText("SDT NV");

        jLabelEmEmail.setText("Email NV");

        jLabelCusName.setText("Tên KH");

        jLabelCusTel.setText("SDT KH");

        jLabelCusAddress.setText("Địa chỉ KH");

        jLabelReceiptID.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelReceiptID.setText("jLabel14");

        jLabelTotalMoney.setText("000.000");
        jLabelTotalMoney.setToolTipText("Tổng tiền phải thanh toán");
        jLabelTotalMoney.setDoubleBuffered(true);

        jButton1.setText("In hóa đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelCashMoney.setText("000.000");
        jLabelCashMoney.setToolTipText("Tổng tiền phải thanh toán");
        jLabelCashMoney.setDoubleBuffered(true);

        jLabelTransferMoney.setText("000.000");
        jLabelTransferMoney.setToolTipText("Tổng tiền phải thanh toán");
        jLabelTransferMoney.setDoubleBuffered(true);

        jTableListCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Biển số", "Dòng xe", "Hãng xe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableListCar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelEmName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabelEmTel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(jLabelCusTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(jLabelEmEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelCusAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonBack)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1)
                            .addGap(392, 392, 392)))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1)
                        .addGap(118, 118, 118)
                        .addComponent(jLabelReceiptID))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCashMoney, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(jLabelTransferMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabelListService))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelListSupply)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(176, 176, 176))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelReceiptID)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234)
                        .addComponent(jLabel26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEmTel)
                            .addComponent(jLabelEmName)
                            .addComponent(jLabelEmEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCusName)
                            .addComponent(jLabelCusTel)
                            .addComponent(jLabelCusAddress))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelListSupply)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabelListService)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTransferMoney)
                            .addComponent(jLabelTotalMoney))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCashMoney)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBack)
                            .addComponent(jButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        IncomeStat incomeStat = null;
        
        // Sử dụng lớp Calendar để trích xuất năm và tháng từ đối tượng Date
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(receipt.getReceiptDate());
        int year = calendar.get(Calendar.YEAR);
        int month = calendar.get(Calendar.MONTH) + 1;
        
        incomeStat = new IncomeStat(month, year, 0);
        
        this.setVisible(false);
        ReceiptStatFrm receiptStatFrm = new ReceiptStatFrm(incomeStat);
        receiptStatFrm.setVisible(true);
        receiptStatFrm.setTitle("Car Garage");
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "This function is under construction!");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiptDetailFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiptDetailFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiptDetailFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiptDetailFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceiptDetailFrm(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCashMoney;
    private javax.swing.JLabel jLabelCusAddress;
    private javax.swing.JLabel jLabelCusName;
    private javax.swing.JLabel jLabelCusTel;
    private javax.swing.JLabel jLabelEmEmail;
    private javax.swing.JLabel jLabelEmName;
    private javax.swing.JLabel jLabelEmTel;
    private javax.swing.JLabel jLabelListService;
    private javax.swing.JLabel jLabelListSupply;
    private javax.swing.JLabel jLabelReceiptID;
    private javax.swing.JLabel jLabelTotalMoney;
    private javax.swing.JLabel jLabelTransferMoney;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableListCar;
    private javax.swing.JTable jTableUsedService;
    private javax.swing.JTable jTableUsedSupply;
    // End of variables declaration//GEN-END:variables
}
