/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ptit.View;

import com.ptit.DAO.ReceiptStatDAO;
import com.ptit.Model.IncomeStat;
import com.ptit.Model.Receipt;
import com.ptit.Model.RepairedCar;
import com.ptit.Model.UsedService;
import com.ptit.Model.UsedSupply;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trang
 */
public class ReceiptStatFrm extends javax.swing.JFrame {
    private IncomeStat incomeStat;
    private ReceiptStatDAO receiptStatDAO;
    private ArrayList<Receipt> receiptStats;

    /**
     * Creates new form ReceiptStatFrm
     */
    public ReceiptStatFrm(IncomeStat incomeStat) {
        initComponents();
        this.incomeStat = incomeStat;
        String monthYear = this.incomeStat.getMonth()+"/"+this.incomeStat.getYear();
        if(monthYear == null) {
            monthYear = "MM/yyyy";
        }

        jLabelDate.setText(monthYear);
        
        receiptStatDAO = new ReceiptStatDAO();
        receiptStats = receiptStatDAO.getReceiptStatByMonth(incomeStat);
        
        if(receiptStats.isEmpty()) {
            jLabelReceiptList.setText("Không có hóa đơn trong tháng");
        } else {
            DefaultTableModel model = (DefaultTableModel) this.jTableReceipt.getModel();
            model.setRowCount(0);
            for (Receipt r : receiptStats) {
//                double totalUssPrice = r.getRepairedCars().getUsedSupplies().stream().mapToDouble(UsedSupply::getPrice).sum();
//                double totalUsPrice = r.getUsedServices().stream().mapToDouble(UsedService::getPrice).sum();
//                double totalPrice = totalUssPrice + totalUsPrice;

                String listCars = ""; // list repaired cars in a receipt
                int totalUsed = 0; // total number of used supplies and services for repaired cars.
                double totalPrice = 0; // total price of used supplies and services for repaired cars.
                
                for (RepairedCar rc : r.getRepairedCars()) {
                    listCars+=rc.getCar().getType() + ", ";
                    totalUsed += rc.getUsedServices().size() + rc.getUsedSupplies().size();
                    totalPrice += rc.getUsedServices().stream().mapToDouble(UsedService::getPrice).sum() + rc.getUsedSupplies().stream().mapToDouble(UsedSupply::getPrice).sum();
                }
                
                model.addRow(new Object[]{
                    r.getId(), 
                    r.getReceiptDate(), 
                    r.getCustomer().getName(), 
                    listCars,
                    totalUsed,
//                    r.getUsedSupplies().size() + r.getUsedServices().size(), 
//                    totalPrice
                    totalPrice
                });
            }
        }
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelReceiptList = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableReceipt = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("Thống kê hóa đơn theo tháng ");

        jLabelReceiptList.setText("Danh sách hóa đơn");

        jLabelDate.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabelDate.setText("jLabel2");

        jTableReceipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "date", "customer name", "car type", "total services/supplies", "total money"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableReceiptMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableReceipt);

        jButton1.setText("Trở lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelReceiptList)
                            .addComponent(jButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelReceiptList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReceiptMouseClicked
        // TODO add your handling code here:
        int index = jTableReceipt.getSelectedRow();
        Receipt receipt = receiptStats.get(index);
        System.out.println(receipt.toString());
        
        if(receipt == null) {
            JOptionPane.showMessageDialog(this, "Hóa đơn không tồn tại!");
        } else {
            this.setVisible(false);
            ReceiptDetailFrm receiptDetailFrm = new ReceiptDetailFrm(receipt);
            receiptDetailFrm.setVisible(true);
            receiptDetailFrm.setTitle("Chi tiết hóa đơn");
        }
    }//GEN-LAST:event_jTableReceiptMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            this.setVisible(false);
            IncomeStatFrm incomeStatFrm = new IncomeStatFrm();
            incomeStatFrm.setVisible(true);
            incomeStatFrm.setTitle("Car Garage");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiptStatFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiptStatFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiptStatFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiptStatFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IncomeStat test = new IncomeStat(3, 2024, 21600000);
                new ReceiptStatFrm(test).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelReceiptList;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableReceipt;
    // End of variables declaration//GEN-END:variables
}
